#!/usr/bin/env bash

# Template from: https://github.com/anishathalye/dotbot/

set -e

# Cross-platform config
CONFIG_COMMON="config_common.yaml"

# Platform-specific config
if [[ `uname` == 'Darwin' ]]; then
    CONFIG_PLT="config_osx.yaml"
elif [[ `uname` == 'Linux' ]]; then
    CONFIG_PLT="config_linux.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_COMMON}" -c "${CONFIG_PLT}" "${@}"
