#!/usr/bin/env bash

set -e

if [[ $(uname) == 'Darwin' ]]; then
    stow --restow --verbose --no-folding common macOS
elif [[ $(uname) == 'Linux' ]]; then
    stow --restow --verbose --no-folding common linux
fi
