#!/usr/bin/env bash

# Copied from: https://github.com/anishathalye/dotbot/blob/master/tools/git-submodule/install

set -e

# Cross platform config
CONFIG_COMMON="install.conf.yaml"

# Platform-specific config
if [[ `uname` == 'Darwin' ]]; then
    CONFIG_PLT="install_osx.conf.yaml"
elif [[ `uname` == 'Linux' ]]; then
    CONFIG_PLT="install_linux.conf.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_COMMON}" -c "${CONFIG_PLT}" "${@}"
