user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("full-screen-api.warning.timeout",-1);
user_pref("full-screen-api.transition-duration.leave", "0 0");
user_pref("full-screen-api.transition-duration.enter", "0 0");
user_pref("services.sync.prefs.sync.browser.uiCustomization.state", true);
user_pref("ui.popup.disable_autohide", false);
user_pref("privacy.webrtc.hideGlobalIndicator", true);
user_pref("privacy.webrtc.legacyGlobalIndicator", false);
user_pref("newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.urlbar.maxRichResults", 5);
user_pref("browser.fullscreen.autohide", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.startup.homepage", "chrome://browser/content/blanktab.html");
