gui:
  nerdFontsVersion: "3"
  showFileTree: true
  showFileIcons: true
  showBranchCommitHash: true
  # matched to Zed "Popping and Locking" theme
  theme:
    activeBorderColor:
      - "#fabd2f"
      - bold
    inactiveBorderColor:
      - "#665c54"
    searchingActiveBorderColor:
      - "#99c6ca"
      - bold
    optionsTextColor:
      - "#fabd2f"
    selectedLineBgColor:
      - "#313242"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#f2e5bc"
    cherryPickedCommitBgColor:
      - "#3e588c"
    markedBaseCommitFgColor:
      - "#1C1D26"
    markedBaseCommitBgColor:
      - "#fabd2f"
    unstagedChangesColor:
      - "#f42c3e"
    defaultFgColor:
      - "#f2e5bc"
  authorColors:
    "*": "#d3869b"
  branchColorPatterns:
    "^feat(ure)?/": "#7ec16e"
    "^fix/": "#f42c3e"
    "^docs/": "#99c6ca"
    "^chore/": "#fabd2f"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
customCommands:
  - key: 'U'
    description: "Push to a specific remote repository"
    context: 'global'
    loadingText: 'Pushing ...'
    prompts:
      - type: 'menuFromCommand'
        title: 'Which remote repository to push to?'
        command: bash -c "git remote --verbose | grep '(push)$'"
        filter: '(?P<remote>.*)\s+(?P<url>.*) \(push\)'
        valueFormat: '{{ .remote }}'
        labelFormat: '{{ .remote | bold | cyan }} {{ .url }}'
      - type: 'menu'
        title: 'How to push?'
        options:
          - value: 'push'
          - value: 'push --force-with-lease'
          - value: 'push --force'
    command: "git {{index .PromptResponses 1}} {{index .PromptResponses 0}}"
