theme = "default_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = true
popup-border = "all"

[editor.file-picker]
hidden = false
ignore = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"

[editor.soft-wrap]
enable = true

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
#C-y = [ ':sh rm -f /tmp/yazi-path', ':insert-output yazi %{buffer_name} --chooser-file=/tmp/yazi-path', ":open %sh{cat /tmp/yazi-path}", ":redraw" ]

[keys.normal.space]
t = ":run-shell-command kitty @ launch --location=vsplit --cwd $(pwd)"
