theme = "kanagawa"

[editor]
line-number = "relative"
trim-trailing-whitespace = true
bufferline = "multiple"
mouse = true
popup-border = "all"
cursorline = true
clipboard-provider = "termcode"
rulers = [88, 120]
gutters = [
  # "diagnostics",
  "spacer",
  "line-numbers",
  "spacer",
  "diff"
]

# Minimum severity of diagnostics
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "disable" # show warnings and errors on the cursorline inline
other-lines = "error"

[editor.lsp]
# display-messages = false
# enable = false

[editor.file-picker]
hidden = false
ignore = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"

[editor.statusline]
right = ["diagnostics", "position-percentage", "file-type"]

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
C-g = [
    ":write-all", # without this the reload-all will get rid of unsaved changes?
    ":noop %sh{kitty @ launch --wait-for-child-to-exit --type=overlay --cwd $(pwd) lazygit}",
    ":redraw",
    ":reload-all"
]

C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

"C-t" = ":sh kitty @ launch --type=overlay --cwd $(pwd) > /dev/null"
"C-`" = ":sh kitty @ launch --location=vsplit --bias -20 --cwd $(pwd) > /dev/null"

"S-h" = ":buffer-previous"
"S-l" = ":buffer-next"

[keys.normal.space.space]
# Show blame info for current line
b = ":sh git -C $(dirname $(realpath %{buffer_name})) blame -L %{cursor_line},%{cursor_line} $(realpath %{buffer_name})"

R = ":lsp-restart"
r = ":lsp-stop"
# p = [
#   ":write-all",
#   ":cd %sh{kitty @ launch --wait-for-child-to-exit --location=vsplit --bias -20 sh -c 'fd . -t d -d 2 ~/repos | fzf'}",
#   ":buffer-close-all",
#   ":redraw"
# ]

# p = ":cd ~/repos/ %sh{cd ~/repos && fd -t d -d 2 | fzf}"
# Problem: no cancel support
p = [
  ":write-all",
  ":cd %sh{cd ~/repos && fd . -t d -d 2 /home/milad/repos | fzf}",
  ":buffer-close-all!",
  ":redraw"
]
"`" = ":sh kitty @ launch --location=vsplit --bias -20 --cwd $(pwd) > /dev/null"
