theme = "kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = true
popup-border = "all"
cursorline = true
clipboard-provider = "termcode"

# Minimum severity of diagnostics
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "error" # show warnings and errors on the cursorline inline
other-lines = "error"

[editor.lsp]
# display-messages = false
# enable = false

[editor.file-picker]
hidden = false
ignore = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
C-g = [
    ":new", 
    ":insert-output lazygit", 
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
"C-t" = ":sh kitty @ launch --location=vsplit --cwd $(pwd) > /dev/null"
