theme = "default_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = true

[editor.file-picker]
hidden = false
ignore = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.normal.space]
t = ":run-shell-command kitty @ launch --location=vsplit --cwd $(pwd)"
