theme = "kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = true
popup-border = "all"
cursorline = true
clipboard-provider = "termcode"

# Minimum severity of diagnostics
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "error" # show warnings and errors on the cursorline inline
other-lines = "error"

[editor.lsp]
# display-messages = false
# enable = false

[editor.file-picker]
hidden = false
ignore = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"

[editor.statusline]
right = ["diagnostics", "position-percentage", "file-type"]

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true

[keys.normal]
C-g = [
    ":write-all", # without this the reload-all will get rid of unsaved changes?
    ":noop %sh{kitty @ launch --type=overlay --cwd $(pwd) lazygit}",
    ":redraw", 
    ":reload-all"
]

C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

"C-t" = ":sh kitty @ launch --type=overlay --cwd $(pwd) > /dev/null"
"C-`" = ":sh kitty @ launch --location=vsplit --bias -20 --cwd $(pwd) > /dev/null"

[keys.normal.z]
"d" = [
  ":toggle inline-diagnostics.cursor-line disable error",
  ":toggle inline-diagnostics.other-lines disable error",
]


[keys.normal.space.space]
# Show blame info for current line
b = ":sh git -C $(dirname $(realpath %{buffer_name})) blame -L %{cursor_line},%{cursor_line} $(realpath %{buffer_name})"

